export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_PROFILE = "LOGOUT";

export const CREATE_BUCKETLIST = "CREATE_BUCKETLIST";
export const FETCH_ALL_BUCKETLIST = "FETCH_ALL_BUCKETLIST";
export const FETCH_BUCKETLIST = "FETCH_BUCKETLIST";
export const CHANGE_BUCKETLIST_MODE = "CHANGE_BUCKETLIST_MODE";

export const VIEW_MODE = "VIEW_MODE";
export const EDIT_ITEM_MODE = "EDIT_ITEM_MODE";
export const EMPTY_MODE = "EMPTY_MODE";
export const EDIT_BUCKETLIST_MODE = "EDIT_BUCKETLIST_MODE";
export const ADD_ITEM_MODE = "ADD_ITEM_MODE";
export const FETCH_ALL_BUCKETLIST_ITEMS = "FETCH_ALL_BUCKETLIST_ITEMS";
